
// Objective-C API for talking to the following Go packages
//
//	github.com/kaleidochain/kaleido/mobile_gengine
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gengine_FRAMEWORK_H__
#define __Gengine_FRAMEWORK_H__

#include "Gengine.objc.h"
#include "Universe.objc.h"

#endif
